title Arch Linux Zen
linux vmlinuz-linux-zen
initrd amd-ucode.img
initrd initramfs-linux-zen.img
options zfs=nvm/root rw quiet loglevel=3 rd.systemd.show_status=false rd.udev.log-priority=3 mitigations=off cgroup_no_v1="all" audit=0
